"""
Auto-generated by the test-generator skill.
Spec sheet: .claude/skills/testcase-generator/generated_spec_sheets/testcases_file_countries_20260521_222624Z.xlsx
Components: countries

Move this file into tests/ after review. Do NOT hand-edit the copy in output/ —
re-run the skill to regenerate.
"""

from __future__ import annotations

import json
import logging
import re
import time
from pathlib import Path
from typing import Any

import allure
import pytest
import pytest_check as check

from src.client import ApiClient, ApiError
from src.validators import validate_countries_schema, validate_population_positive

LOG = logging.getLogger(__name__)

pytestmark = pytest.mark.regression

_CASES_PATH = (
    Path(__file__).resolve().parents[2]
    / "test_data"
    / "countries"
    / "test_data_countries_generated_20260521_230754Z.json"
)
_PLACEHOLDER_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")


def _load_cases() -> dict[str, dict[str, list[dict[str, Any]]]]:
    """Load grouped test cases from the companion JSON file."""
    with _CASES_PATH.open(encoding="utf-8") as fh:
        return dict(json.load(fh))


def _safe_path(template: str, params: dict[str, Any] | None) -> str:
    """Substitute {placeholder} fields. Missing keys default to 'missing'."""
    params = params or {}
    defaults = {p: str(params.get(p, "missing")) for p in _PLACEHOLDER_RE.findall(template)}
    return template.format(**defaults)


_ALL_CASES = _load_cases()


def _cases(class_key: str, bucket: str) -> list[dict[str, Any]]:
    """Return the list of parametrize entries for one class + bucket."""
    return list(_ALL_CASES.get(class_key, {}).get(bucket, []))



@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31All:
    """Tests for GET /all — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/all"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get("/all", params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        items = data if isinstance(data, list) else [data]
        assert items, "expected a non-empty country list"
        for _country in items:
            with check.check:
                validate_population_positive(_country)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get("/all", params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get("/all", params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            items = data if isinstance(data, list) else [data]
            assert items, "expected a non-empty country list"
            for _country in items:
                with check.check:
                    validate_population_positive(_country)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get("/all", params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31NameName:
    """Tests for GET /name/{name} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/name/{name}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/name/{name}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/name/{name}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/name/{name}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/name/{name}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31AlphaCode:
    """Tests for GET /alpha/{code} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/alpha/{code}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/alpha/{code}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/alpha/{code}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/alpha/{code}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/alpha/{code}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31Alpha:
    """Tests for GET /alpha — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/alpha"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get("/alpha", params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get("/alpha", params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get("/alpha", params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get("/alpha", params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31CapitalCapital:
    """Tests for GET /capital/{capital} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/capital/{capital}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/capital/{capital}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/capital/{capital}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/capital/{capital}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/capital/{capital}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31CurrencyCurrency:
    """Tests for GET /currency/{currency} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/currency/{currency}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/currency/{currency}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/currency/{currency}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/currency/{currency}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/currency/{currency}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31LangLanguage:
    """Tests for GET /lang/{language} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/lang/{language}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/lang/{language}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/lang/{language}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/lang/{language}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/lang/{language}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31RegionRegion:
    """Tests for GET /region/{region} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/region/{region}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/region/{region}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/region/{region}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/region/{region}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/region/{region}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31SubregionSubregion:
    """Tests for GET /subregion/{subregion} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/subregion/{subregion}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/subregion/{subregion}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/subregion/{subregion}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/subregion/{subregion}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/subregion/{subregion}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31DemonymDemonym:
    """Tests for GET /demonym/{demonym} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/demonym/{demonym}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/demonym/{demonym}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/demonym/{demonym}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/demonym/{demonym}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/demonym/{demonym}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31TranslationTranslation:
    """Tests for GET /translation/{translation} — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/translation/{translation}"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get(_safe_path("/translation/{translation}", case.get("path_params")), params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get(_safe_path("/translation/{translation}", case.get("path_params")), params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get(_safe_path("/translation/{translation}", case.get("path_params")), params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get(_safe_path("/translation/{translation}", case.get("path_params")), params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


@allure.feature("Countries API — GET https")
@pytest.mark.countries
class TestGetRestcountriesComV31Independent:
    """Tests for GET /independent — generated from spec sheet."""

    _CLASS_KEY = "countries__GET__/independent"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get("/independent", params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        payload = data[0] if isinstance(data, list) and data else data
        validate_countries_schema(payload)

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get("/independent", params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get("/independent", params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            payload = data[0] if isinstance(data, list) and data else data
            validate_countries_schema(payload)
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get("/independent", params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


