"""Walk a parsed schema dict and emit a Python validator file."""
from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path
from typing import Any

LOG = logging.getLogger(__name__)

_INDENT = "    "

# Maps schema-type → (Python isinstance argument, human-friendly type name)
_PRIMITIVE_PY = {
    "string":  ("str",          "str"),
    "integer": ("int",          "int"),
    "number":  ("(int, float)", "number"),
    "boolean": ("bool",         "bool"),
}


def emit(schema: dict[str, Any]) -> str:
    """Return the full Python file contents (assert-based validator)."""
    component = schema["component"]
    validator_name = schema["validator_name"]
    description = schema.get("description", "")
    shape = schema["shape"]
    timestamp = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")

    body_lines = _walk(shape, access="data", indent=1)

    header = (
        '"""\n'
        f'Auto-generated by validator-generator skill.\n'
        f'Component:     {component}\n'
        f'Generated UTC: {timestamp}\n'
        f'\n'
        f'Move the function below into src/validators.py — or re-run the skill\n'
        f'with --write-to-validators to do that automatically.\n'
        '"""\n'
        'from __future__ import annotations\n'
        '\n'
        'from typing import Any\n'
        '\n'
        '\n'
    )
    func = [f"def {validator_name}(data: dict[str, Any]) -> None:"]
    if description:
        func.append(f'{_INDENT}"""{description}"""')
    func.extend(body_lines)
    return header + "\n".join(func) + "\n"


def _walk(node: dict[str, Any], *, access: str, indent: int) -> list[str]:
    """Emit assertion lines for one schema node (recursive)."""
    t = node["type"]
    if t == "object":
        return _walk_object(node, access, indent)
    if t == "array":
        return _walk_array(node, access, indent)
    # Primitive (with modifiers)
    return _walk_primitive(node, access, indent)


def _walk_object(node: dict[str, Any], access: str, indent: int) -> list[str]:
    pad = _INDENT * indent
    lines: list[str] = [
        f"{pad}assert isinstance({access}, dict), "
        f'f"{access} must be dict, got {{type({access}).__name__}}"',
    ]
    required = list(node.get("required") or [])
    fields: dict[str, Any] = node.get("fields") or {}

    if required:
        tup = ", ".join(repr(r) for r in required)
        lines.append(f"{pad}for _required in ({tup},):")
        lines.append(
            f"{pad}{_INDENT}assert _required in {access}, "
            f'f"missing required field: {access}.{{_required}}"'
        )

    for name, sub in fields.items():
        sub_access = f"{access}[{name!r}]"
        sub_lines = _walk(sub, access=sub_access, indent=indent)
        if name in required:
            lines.extend(sub_lines)
        else:
            lines.append(f"{pad}if {name!r} in {access}:")
            lines.extend(_INDENT + s for s in sub_lines)
    return lines


def _walk_array(node: dict[str, Any], access: str, indent: int) -> list[str]:
    pad = _INDENT * indent
    lines: list[str] = [
        f"{pad}assert isinstance({access}, list), "
        f'f"{access} must be list, got {{type({access}).__name__}}"',
    ]
    if node.get("non_empty"):
        lines.append(f"{pad}assert len({access}) > 0, "
                     f'"{access} must be non-empty"')
    if "min_length" in node:
        ml = node["min_length"]
        lines.append(f"{pad}assert len({access}) >= {ml}, "
                     f'"{access} must have at least {ml} items"')
    if "max_length" in node:
        ml = node["max_length"]
        lines.append(f"{pad}assert len({access}) <= {ml}, "
                     f'"{access} must have at most {ml} items"')
    item_type = node["item_type"]
    if item_type != "any":
        lines.append(f"{pad}for _item in {access}:")
        item_node = {"type": item_type}
        lines.extend(_walk(item_node, access="_item", indent=indent + 1))
    return lines


def _walk_primitive(node: dict[str, Any], access: str, indent: int) -> list[str]:
    pad = _INDENT * indent
    t = node["type"]
    lines: list[str] = []

    if t == "number_or_null":
        lines.append(
            f"{pad}assert {access} is None or isinstance({access}, (int, float)), "
            f'"{access} must be number or null"'
        )
        return lines
    if t == "string_or_null":
        lines.append(
            f"{pad}assert {access} is None or isinstance({access}, str), "
            f'"{access} must be string or null"'
        )
        return lines

    pytype, label = _PRIMITIVE_PY[t]
    lines.append(f"{pad}assert isinstance({access}, {pytype}), "
                 f'"{access} must be {label}"')

    if t == "string" and node.get("non_empty"):
        lines.append(f"{pad}assert len({access}) > 0, "
                     f'"{access} must be non-empty string"')
    if t in ("integer", "number") and "min" in node:
        mn = node["min"]
        lines.append(f'{pad}assert {access} >= {mn}, '
                     f'"{access} must be >= {mn}"')
    if t in ("integer", "number") and "max" in node:
        mx = node["max"]
        lines.append(f'{pad}assert {access} <= {mx}, '
                     f'"{access} must be <= {mx}"')
    return lines


def write_file(out_dir: Path, schema: dict[str, Any]) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d_%H%M%SZ")
    name = f"validate_{schema['component']}_{ts}.py"
    path = out_dir / name
    path.write_text(emit(schema), encoding="utf-8")
    LOG.info("Wrote validator %s", path)
    return path
