"""
Auto-generated by the test-generator skill.
Spec sheet: .claude/skills/testcase-generator/generated_spec_sheets/testcases_file_weather_20260522_004749Z.xlsx
Components: weather

Move this file into tests/ after review. Do NOT hand-edit the copy in output/ —
re-run the skill to regenerate.
"""

from __future__ import annotations

import json
import logging
import re
import time
from pathlib import Path
from typing import Any

import allure
import pytest

from src.client import ApiClient, ApiError
from src.validators import validate_weather_response

LOG = logging.getLogger(__name__)

pytestmark = pytest.mark.regression

_CASES_PATH = (
    Path(__file__).resolve().parents[2]
    / "test_data"
    / "weather"
    / "test_data_weather_generated_20260522_010623Z.json"
)

_PLACEHOLDER_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")


def _load_cases() -> dict[str, dict[str, list[dict[str, Any]]]]:
    """Load grouped test cases from the companion JSON file."""
    with _CASES_PATH.open(encoding="utf-8") as fh:
        return dict(json.load(fh))


def _safe_path(template: str, params: dict[str, Any] | None) -> str:
    """Substitute {placeholder} fields. Missing keys default to 'missing'."""
    params = params or {}
    defaults = {p: str(params.get(p, "missing")) for p in _PLACEHOLDER_RE.findall(template)}
    return template.format(**defaults)


_ALL_CASES = _load_cases()


def _cases(class_key: str, bucket: str) -> list[dict[str, Any]]:
    """Return the list of parametrize entries for one class + bucket."""
    return list(_ALL_CASES.get(class_key, {}).get(bucket, []))



@allure.feature("Weather API — GET /forecast")
@pytest.mark.weather
class TestGetForecast:
    """Tests for GET /forecast — generated from spec sheet."""

    _CLASS_KEY = "weather__GET__/forecast"

    @allure.story("Happy path")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "positive"), ids=lambda c: c["tc_id"],
    )
    def test_positive(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Happy path — one parametrize entry per TC_ in the spec sheet."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] positive: %s", case["tc_id"], case["title"])
        data = api_client.get("/forecast", params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        validate_weather_response(
            data,
            temp_min=float(env_config["temperature_min_c"]),
            temp_max=float(env_config["temperature_max_c"]),
        )

    @allure.story("Response schema")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "schema"), ids=lambda c: c["tc_id"],
    )
    def test_schema(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Validate the response body via the per-component validator."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] schema: %s", case["tc_id"], case["title"])
        data = api_client.get("/forecast", params=case.get("query_params") or {})
        assert data is not None, case["tc_id"]
        validate_weather_response(
            data,
            temp_min=float(env_config["temperature_min_c"]),
            temp_max=float(env_config["temperature_max_c"]),
        )

    @allure.story("Negative cases")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "negative"), ids=lambda c: c["tc_id"],
    )
    def test_negative(self, api_client: ApiClient, case: dict[str, Any]) -> None:
        """Expect documented non-2xx. ApiClient raises ApiError on !2xx."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] negative: %s", case["tc_id"], case["title"])
        with pytest.raises(ApiError) as exc:
            api_client.get("/forecast", params=case.get("query_params") or {})
        assert exc.value.status_code == case["expected_status"], (
            f"{case['tc_id']}: expected {case['expected_status']}, "
            f"got {exc.value.status_code}"
        )

    @allure.story("Edge / boundary / i18n")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "edge"), ids=lambda c: c["tc_id"],
    )
    def test_edge(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Boundary and i18n cases — either succeed or surface the documented code."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] edge: %s", case["tc_id"], case["title"])
        try:
            data = api_client.get("/forecast", params=case.get("query_params") or {})
            assert data is not None, case["tc_id"]
            validate_weather_response(
                data,
                temp_min=float(env_config["temperature_min_c"]),
                temp_max=float(env_config["temperature_max_c"]),
            )
        except ApiError as exc:
            assert exc.status_code == case["expected_status"], (
                f"{case['tc_id']}: expected {case['expected_status']}, "
                f"got {exc.status_code}"
            )

    @allure.story("Response time threshold")
    @pytest.mark.parametrize(
        "case", _cases(_CLASS_KEY, "performance"), ids=lambda c: c["tc_id"],
    )
    def test_performance(
        self, api_client: ApiClient, env_config: dict[str, Any], case: dict[str, Any],
    ) -> None:
        """Threshold from env_config["max_response_time"] — never hardcoded."""
        if case.get("skip"):
            pytest.skip(case.get("skip_reason", "auto-skipped"))
        LOG.info("[%s] performance: %s", case["tc_id"], case["title"])
        start = time.monotonic()
        api_client.get("/forecast", params=case.get("query_params") or {})
        elapsed_ms = (time.monotonic() - start) * 1000
        threshold_ms = float(env_config["max_response_time"]) * 1000
        assert elapsed_ms <= threshold_ms, (
            f"{case['tc_id']}: {elapsed_ms:.0f}ms > {threshold_ms:.0f}ms"
        )


